#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gemserv"
name = "Gemserv"
description.en = "Gemini server"
description.fr = "Serveur Gemini"

version = "0.6.7~ynh1"

maintainers = []

[upstream]
license = "MIT"
code = "https://git.sr.ht/~int80h/gemserv"
website = "https://git.sr.ht/~int80h/gemserv/"

[integration]
yunohost = ">= 11.2.27"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "100M"
ram.build = "500M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources.main]
    url = "https://github.com/calacuda/gemserv/archive/refs/tags/v0.6.7.zip"
    sha256 = "ee88ec11addad17c4acfb0dbfec12c0489c15fa6099151a3eedca45a0c6eb274"

    [resources.system_user]

    [resources.ports]
    main.default = 1965
    main.exposed = "TCP"
    main.fixed = true

    [resources.install_dir]

    [resources.permissions]

    [resources.apt]
    packages = ["pkg-config", "libssl-dev"]
