#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gemserv"
name = "Gemserv"
description.en = "Gemini server"
description.fr = "Serveur Gemini"

version = "0.6.7~ynh1"

maintainers = []

[upstream]
license = "MIT"
website = "https://github.com/calacuda/gemserv/"
code = "https://github.com/calacuda/gemserv/"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "100M"
ram.build = "500M"
ram.runtime = "50M"

[install]

[resources]

    [resources.sources.main]
    url = "https://github.com/calacuda/gemserv/archive/refs/tags/v0.6.7.zip"
    sha256 = "ee88ec11addad17c4acfb0dbfec12c0489c15fa6099151a3eedca45a0c6eb274"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)


    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    main.default = 1965
    main.exposed = "TCP"
    main.fixed = true

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = [
        "pkg-config",
        "curl",
        "build-essential",
        "gcc",
        "make",
        "libssl-dev"
        ]
