#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================

# Backup the systemd service unit
ynh_backup "/etc/systemd/system/$app.service"

# Backup the logrotate configuration
ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/etc/$app/"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
