#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir/build"

mkdir -p "$install_dir/live"

chown -R "$app:$app" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

mkdir -p "/etc/$app/config.d/"

chmod 750 "/etc/$app"
chmod -R o-rwx "/etc/$app"
chown -R "$app:$app" "/etc/$app"

ynh_config_add --template="server.toml" --destination="/etc/$app/config.d/server.toml.head"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd

yunohost service add "$app" --description="$app daemon" --log="/var/log/$app/$app.log" --needs_exposed_ports="1965"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate

#=================================================
# CONFIGURING SYSTEM USER
#=================================================
ynh_script_progression "Configuring system user..."

usermod -a -G ssl-cert "$app"

#=================================================
# INSTALL RUST/CARGO
#=================================================
ynh_script_progression "Installing Rust and Cargo..."

# Install rustup with the toolchain needed by Gemserv
pushd "$install_dir"
    ynh_hide_warnings ynh_exec_as_app \
        RUSTUP_HOME="$install_dir/.rustup" \
        CARGO_HOME="$install_dir/.cargo" \
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | ynh_hide_warnings ynh_exec_as_app sh -s -- -q -y
popd

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

# Compile Gemserv
pushd "$install_dir/build"
    ynh_hide_warnings ynh_exec_as_app bash -c "source $install_dir/.cargo/env; cargo build --release"
popd

# Install Gemserv
cp -af "$install_dir/build/target/release/gemserv" "$install_dir/live/gemserv"

# Remove build files and rustup
ynh_safe_rm "$install_dir/build"
ynh_safe_rm "$install_dir/.cargo"
ynh_safe_rm "$install_dir/.rustup"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="Started" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
